[workspace]
members = [
    "packages/studentvue-api",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
