[package]
name = "studenvue"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
authors = ["studenvue"]
license = "MIT"
description = "Rust client library for the StudentVue SOAP API"
repository = "https://github.com/studenvue/studenvue"
keywords = ["studentvue", "api", "soap", "education"]
categories = ["api-bindings", "web-programming::http-client"]

[dependencies]
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1.35", features = ["full"] }
quick-xml = { version = "0.31", features = ["serialize"] }
thiserror = "1.0"
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.4"

